import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c5c6cd",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bcc7de",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "on-surface": "#0b1c30",
        "on-primary-container": "#8590a6",
        "on-secondary-fixed-variant": "#474743",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5516be",
        "on-secondary-container": "#656461",
        "on-tertiary-container": "#9f77ff",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bcc7de",
        "surface-tint": "#545f73",
        "tertiary-fixed": "#e9ddff",
        "primary-container": "#1e293b",
        "primary-fixed": "#d8e3fb",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "tertiary": "#1a0049",
        "on-primary-fixed-variant": "#3c475a",
        "secondary-fixed": "#e5e2dd",
        "secondary": "#5f5e5b",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#c8c6c2",
        "surface": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#45474c",
        "outline": "#75777d",
        "tertiary-container": "#32007d",
        "secondary-container": "#e5e2dd",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed": "#1c1c19",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "primary": "#091426",
        "on-primary-fixed": "#111c2d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "32px",
        unit: "4px",
        "stack-sm": "8px",
        gutter: "24px",
        "stack-md": "16px",
        "container-padding": "32px",
        "sidebar-width": "425px",
      },
      fontFamily: {
        "body-lg": ["Source Sans 3"],
        "body-md": ["Source Sans 3"],
        "label-caps": ["JetBrains Mono"],
        "headline-sm": ["Source Serif 4"],
        "display-lg": ["Source Serif 4"],
        "mono-data": ["JetBrains Mono"],
        "headline-md": ["Source Serif 4"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
